import os
import re

def format_timestamp_ass(seconds: float) -> str:
    """Format seconds into ASS timestamp format: H:MM:SS.cs"""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = seconds % 60
    cs = int(round((s - int(s)) * 100))
    if cs == 100:
        cs = 99  # Cap to prevent overflow
    s_int = int(s)
    return f"{h}:{m:02d}:{s_int:02d}.{cs:02d}"

def clean_text_for_ass(text: str) -> str:
    """Escape special characters for ASS"""
    text = text.replace('\n', '\\N')
    # Remove simple markdown-like characters or extra quotes if any
    return text.strip()

def segments_to_ass(segments: list, output_path: str, video_width: int = 720, video_height: int = 1280) -> None:
    """
    Write segments (list of dict with 'start', 'end', 'text') to an ASS subtitle file.
    Uses elegant, professional typography, drop shadow, and stroke.
    """
    dirname = os.path.dirname(output_path)
    if dirname:
        os.makedirs(dirname, exist_ok=True)
    
    ass_header = f"""[Script Info]
; Script generated by Antigravity Translify Engine
Title: Video Subtitles
ScriptType: v4.00+
WrapStyle: 0
PlayResX: {video_width}
PlayResY: {video_height}
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Outfit,32,&H00FFFFFF,&H000000FF,&H00000000,&H60000000,-1,0,0,0,100,100,0,0,1,3.5,2.0,2,40,40,90,1
Style: Caption,Inter,36,&H0000E6FF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,4.0,2.5,5,40,40,120,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(ass_header)
        for seg in segments:
            start_str = format_timestamp_ass(seg.get('start', 0.0))
            end_str = format_timestamp_ass(seg.get('end', 1.0))
            text = clean_text_for_ass(seg.get('text', ''))
            style = seg.get('style', 'Default')
            # Dialogue line
            f.write(f"Dialogue: 0,{start_str},{end_str},{style},,0,0,0,,{text}\n")

def segments_to_srt(segments: list, output_path: str) -> None:
    """Write segments to basic SRT format as fallback"""
    dirname = os.path.dirname(output_path)
    if dirname:
        os.makedirs(dirname, exist_ok=True)
    
    def format_timestamp_srt(seconds: float) -> str:
        h = int(seconds // 3600)
        m = int((seconds % 3600) // 60)
        s = seconds % 60
        ms = int(round((s - int(s)) * 1000))
        if ms == 1000:
            ms = 999
        s_int = int(s)
        return f"{h:02d}:{m:02d}:{s_int:02d},{ms:03d}"
        
    with open(output_path, 'w', encoding='utf-8') as f:
        for idx, seg in enumerate(segments, 1):
            start_str = format_timestamp_srt(seg.get('start', 0.0))
            end_str = format_timestamp_srt(seg.get('end', 1.0))
            text = seg.get('text', '').strip()
            f.write(f"{idx}\n{start_str} --> {end_str}\n{text}\n\n")
